### ISSUE TITLE
Consider to add supported protocol versions by CVO

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-manager-cloud-volumes-ontap#10]
Page: [Provision storage](https://docs.netapp.com/us-en/occm/task_provisioning_storage.html)

Not sure if this is the best place to add the information but doing some research was not able to find the versions of the protocols supported by CVO in the docs.

Could we add the versions at least here:
Create volume -> Steps -> 3 -> b. Protocol

And the kind of information could be a more detailed protocol version as an example:
Instead of NFS (only), add a note Supported NFS versions are NFSv3, NFSv4.1, etc

Regards.

**Comment by netapp-bcammett** [comment]
Gabriel,

Here's the new page. I added a links to it from several other pages, including the volume creation page that you mentioned.
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-client-protocols.html

Thanks again for the feedback.

Regards,
Ben
