### ISSUE TITLE
Procedure to add additional SVMs to Azure HA CVO are Incorrect

### ISSUE THREAD

**Issue by scottkntap** [NetAppDocs/cloud-manager-cloud-volumes-ontap#102]
Page: [Create data-serving storage VMs for Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html)

The steps to add an additional SMB SVM on an HA CVO in Azure need to be updated to specify:

1. **Not** to create a FIP and associated health probe and LB rules for the iSCSI LIFs.  Currently the docs give the impression a FIP is required.
2. The steps and screenshots to add the IP Configuration to the vNICs on each of the CVO nodes for the new SVM iSCSI LIFs created in ONTAP.

**Comment by netapp-driley** [comment]
Hi Scott - Thank you so much for your feedback. We'll review the changes for this item and keep you posted once the revisions are available.

Thanks!

**Comment by scottkntap** [comment]
Has this been updated with the submitted changes?  I don’t see any change from the original version of the doc.

Thanks


Best Regards,


Scott Kovacs
Azure Customer Success Engineer
Public Cloud Services

NetApp
919.476.4560 Direct Phone
919.946.3044 Mobile Phone
***@***.******@***.***>

[signature_1349384773][signature_2607182845]

***@***.***?anonymous&ep=signature>Book time to meet with ***@***.***?anonymous&ep=signature>

UPCOMING OUT OF OFFICE: None

[A picture containing text  Description automatically generated]

[signature_2569672766]<https://www.facebook.com/NetApp>   [signature_2645868705] <https://www.instagram.com/netapp/>    [signature_748460335] <https://www.youtube.com/netapp>    [signature_1729390183] <https://www.linkedin.com/company/netapp/>    [signature_2813808871] <https://twitter.com/NetApp>

From: Chanda Jha ***@***.***>
Date: Thursday, February 23, 2023 at 03:30
To: NetAppDocs/cloud-manager-cloud-volumes-ontap ***@***.***>
Cc: Kovacs, Scott ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/cloud-manager-cloud-volumes-ontap] Procedure to add additional SVMs to Azure HA CVO are Incorrect (Issue #102)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



@netapp-driley<https://github.com/netapp-driley>: This issue will be closed on 02-March due to lack of activity within the last 90 days. If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by netapp-driley** [comment]
My apologies, This item had fallen into my backlog. I will re prioritize this item and resolve as soon as possible. I will provide an update on the documentation status once complete. 

Thank you for your understanding, 

Don Riley

**Comment by netapp-driley** [comment]
Topic updated: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html#ha-pair-2
