### ISSUE TITLE
Clarify IP address creation process - split ILB FIPs for Data/Mgmt from NIC0 direct IP adds for iSCSI

### ISSUE THREAD

**Issue by wjthompson-ntap** [NetAppDocs/cloud-manager-cloud-volumes-ontap#103]
Page: [Create data-serving storage VMs for Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html)

Under the HA-SMB steps for configuring Azure IP addresses, it should be called out that FIPs should _**NOT**_ be created on the Azure load balancer, but instead under NIC0 of the respective VMs themselves.

Section below with modifications.  A screenshot and step by step process of adding the IP address to VM's NIC0 may also be helpful.

----------------------------------------------------

IP addresses that you use for SMB data are allocated in the load balancer so that the IP addresses can migrate to the other node in case failover events occur.

You’ll need to create the following IP addresses: **<-- in the load balancer**

One IP address for NAS data LIF access from node 1

One IP address for NAS data LIF access from node 2

One IP address for an iSCSI LIF on node 1 **<-- in each VM's respective NIC0**

One IP address for an iSCSI LIF on node 2

The iSCSI LIFs are required for DNS and SMB communication. An iSCSI LIF is used for this purpose because it doesn’t migrate on failover.

An optional IP address for a storage VM (SVM) management LIF

This management LIF provides a connection to management tools like SnapCenter.

Steps
In the Azure portal, open the Load balancers service.

Click the name of the load balancer for the HA pair.

Create the required number of frontend IP configurations: **<-- should note ONLY for the data and SVM LIFs**

Under Settings, click Frontend IP configuration.

Click Add.

**Comment by netapp-driley** [comment]
Hi WJ - Thank you so much for your feedback. We'll review the changes for this item and keep you posted once the revisions are available.

Thanks!

**Comment by netapp-driley** [comment]
My apologies, This item had fallen into my backlog. I will re prioritize this item and resolve as soon as possible. I will provide an update on the documentation status once complete. 

Thank you for your understanding, 

Don Riley

**Comment by netapp-driley** [comment]
Topic updated: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html#ha-pair-2
