### ISSUE TITLE
Addtional S3 end points need adding to the documentation

### ISSUE THREAD

**Issue by SteWinfield** [NetAppDocs/cloud-manager-cloud-volumes-ontap#106]
Cloud Volumes ONTAP supports S3 as an option for scale-out storage in the following cloud providers:
 
should we also not be adding GCS (google cloud stroage here)?

**Comment by netapp-rlithman** [comment]
Hi Steve. Thanks for reaching out. Google Cloud is not listed because it is not supported. You can refer to a list of supported functionalities with ONTAP S3 at https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-interoperability-concept.html.
