### ISSUE TITLE
Incomplete instructions

### ISSUE THREAD

**Issue by kris1254** [NetAppDocs/cloud-manager-cloud-volumes-ontap#107]
Page: [Create data-serving storage VMs for Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html)

SMB CVO HA doc says to provision front end ip's but does not explain to provision ip's for iSCSI on nic instead.

**Comment by netapp-bcammett** [comment]
@kris1254, thank you for submitting this issue.

@netapp-driley, can you please assess this feedback alongside these issues: #102 and #103

**Comment by louvipi** [comment]
Looking for an update on this issue.  Many thanks y'all.

**Comment by netapp-driley** [comment]
Hi all -  I plan to sync up engineering to determine what changes are needed for this item. I will  keep you posted once the revisions are complete and published. 

Thank you!

**Comment by netapp-driley** [comment]
My apologies, This item had fallen into my backlog. I will re prioritize this item and resolve as soon as possible. I will provide an update on the documentation status once complete. 

Thank you for your understanding, 

Don Riley

**Comment by netapp-driley** [comment]
Topic updated: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html#ha-pair-2
