### ISSUE TITLE
generate fr and de - 4433

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/cloud-manager-cloud-volumes-ontap#110]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by netapp-bcammett** [comment]
I just made an update to the repo: 
https://github.com/NetAppDocs/cloud-manager-cloud-volumes-ontap/pull/111

**Comment by netapp-gudugunti** [comment]
Site is up and running.
Total TOT: 6 minutes.
