### ISSUE TITLE
Storage account limits

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-cloud-volumes-ontap#115]
Page: [Use an Azure Private Link or service endpoints](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-enabling-private-link.html)

There is a limit mentioned for storage accounts. Where is this limit coming from? I already saw many storage accounts containing much more than 32TB and no new ones were created.

"creating a new storage account when going above 32 TiB"

Thx
Holger

**Comment by netapp-rlithman** [comment]
Hi Holger. Thanks for your question. I'm going to follow up with you and our subject-matter expert via email to get more information.

**Comment by netapp-rlithman** [comment]
Hi Holger. BlueXP limits each storage account to be 35 TiB. The 32 TiB limit comes from Cloud Volumes ONTAP. You can read more about scale targets for premium page blob accounts in [Microsoft Azure's documentation.](https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets-premium-page-blobs)
