### ISSUE TITLE
Wrong redirection link

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/cloud-manager-cloud-volumes-ontap#122]
Page: [Launching Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-gcp.html)

Hello,

In the sections "Edit Project" for both SN and HA procedure there this info "This is the service account that you set up for BlueXP, as described on this page." that redirects to this link: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-creating-gcp-service-account.html

The link is not the correct one because it is referring to the service account needed for tiering and backups.

The correct link, describing the service account that you set up for BlueXP, should be this one: https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-gcp.html#set-up-a-service-account-for-the-connector

**Comment by netapp-rlithman** [comment]
Hi Marco. Thanks for letting us know. I updated the link.
