### ISSUE TITLE
S3 multi-protocol access for NAS client in CVO 9.12.1

### ISSUE THREAD

**Issue by netapptakayuki** [NetAppDocs/cloud-manager-cloud-volumes-ontap#126]
Page: [Client protocols](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-client-protocols.html)

Would you please add the description of S3 multi-protocol access in CVO 12.1.1 to S3 section ?
"Clients can access the same files using both NFS, SMB and S3 protocols." ?

**Comment by netapp-rlithman** [comment]
Hi Takayuki. Thank you for sharing the suggested update. Does this S3 multi-protocol capability to access the same files using NFS, SMB, and S3 protocols apply to other CVO versions or only CVO 9.12.1?

**Comment by netapp-rlithman** [comment]
The page has been updated to include a link to ONTAP documentation about how S3 multiprotocol works. Thank you.
