### ISSUE TITLE
Cloud Volumes Edge Cache instances mistake

### ISSUE THREAD

**Issue by pablogarciaarevalo** [NetAppDocs/cloud-manager-cloud-volumes-ontap#127]
Page: [Cloud Volumes ONTAP licensing](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html)

Based on the public website https://bluexp.netapp.com/pricing, the Cloud Volumes Edge Cache license includes a (10) ten cache instances.

The doc states that includes (6) six edge nodes:
_30 TiB minimum with six edge nodes included_

It should be said:
_30 TiB minimum with ten edge nodes included_

**Comment by netapp-rlithman** [comment]
Thank you for letting us know. The page has been updated.
