### ISSUE TITLE
Additional Reference to MSFT Zonal Disk Support

### ISSUE THREAD

**Issue by scottkntap** [NetAppDocs/cloud-manager-cloud-volumes-ontap#130]
Page: [High-availability pairs in Azure](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html)

I think we need to add information regarding the support of M-AZ and how this ties in with MSFT's support for ZRS managed disks.  The multi-AZ section on this page as well as, or maybe more appropriately the release notes section should contain a statement that we are bound by the regions where MSFT supports ZRS managed disk and link to their docs on this (below).  In addition, explain that this will grow with microsoft's expanded support of ZRS managed disk in additional regions as they are added. This will clarify why we don't offer M-AZ except in what appears to be a subset of global regions.  
 
 https://learn.microsoft.com/en-us/azure/virtual-machines/disks-redundancy#zone-redundant-storage-for-managed-disks

**Comment by netapp-rlithman** [comment]
Hi Scott. Thank you for sharing this with us. I'll take this back to the team and loop you in when we've drafted an update.

**Comment by netapp-rlithman** [comment]
Updates to the below pages were made based on your suggestions. Thanks, Scott! 

[High-availability pairs in Azure](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html#ha-multiple-availability-zone-configuration)
[Cloud Volumes ONTAP Release Notes What’s new](https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-new.html#azure-ha-in-a-single-availability-zone-with-shared-managed-disks)
