### ISSUE TITLE
The specific URLs need to be clear for the HA mediator outbound rule

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/cloud-manager-cloud-volumes-ontap#134]
Page: [Security group rules for AWS](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/reference-security-groups.html)

As the customer is using a firewall instead of VPC endpoint, they need to know the URL of the below outbound ports for the HA mediator :

Protocol	Port	Destination
HTTP		80		Connector IP address  --> what are the specific URLs for this ?
HTTPS		443		AWS API services  --> what are the specific URLs for this ?
UDP			53		AWS API services  --> what are the specific URLs for this ?

Could you please give us a quick response for this request as the customer is preparing infrastructure?

**Comment by Xinwei-Wang** [comment]
For the destination URL , I think it should be the below info, please check and help to add it to the doc.

Protocol Port Destination
HTTP 80 Connector IP address -->IP address of the Connector on AWS EC2 instance
HTTPS 443 AWS API services --> ec2.amazonaws.com
UDP 53 AWS API services --> ec2.amazonaws.com

refered below:
https://docs.aws.amazon.com/general/latest/gr/rande.html

**Comment by netapp-rlithman** [comment]
Thank you, Xinwei. I'll bring it up with the team and loop you in to discuss the issue.

**Comment by netapp-rlithman** [comment]
We updated the page with your recommendations. Thank you for your contribution.
