### ISSUE TITLE
Missing connector firewall rules

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/cloud-manager-cloud-volumes-ontap#139]
Page: [Networking requirements for Cloud Volumes ONTAP in Google Cloud](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/reference-networking-gcp.html)

Hello, I can't find the firewall rules needed for the connector. It is possible to add which ports need to be opened for the connector ?

**Comment by netapp-bcammett** [comment]
Hi Marco,

Thank you for submitting this feedback. The firewall rules for the Connector are documented in the Setup and Admin docs where we describe how to get up and running with BlueXP and perform administration tasks.

To make this clear, I added two links to the page that you referenced:

Link 1
![image](https://user-images.githubusercontent.com/18287750/217570373-d8acb729-d1fd-4802-b391-925ea221154a.png)

Link 2
![image](https://user-images.githubusercontent.com/18287750/217570568-4d8b347a-1488-4c5f-95bd-236d4111f01a.png)

I made similar changes to the AWS and Azure pages as well.

Thanks again for your feedback and please let us know if you have any additional suggestions.
