### ISSUE TITLE
WORM can't be activated after CVO deployment. 

### ISSUE THREAD

**Issue by Dariukuss** [NetAppDocs/cloud-manager-cloud-volumes-ontap#147]
Page: [WORM storage](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-worm.html)

Hello team, 

So here, in this sentence - "If you disable WORM storage when creating a working environment" -> then it says you can enable per volume later on, but there is no way to enable WORM at the CVO level later on. 

I can think about 1) Explaining Product BU will need to connect and enable it 2) remove that sentence to avoid customer's trying to enable WORM per volume in a Non-WORM CVO system - or detailed "How to enable WORM in an already deployed CVO" - Because is not possible (From what I've learn)

BR ! 

Dario

**Comment by netapp-rlithman** [comment]
Hi dariukuss. Thank you for your feedback. Our team recently updated this page. The second bullet now states: 

- If you disable WORM storage when creating a working environment, every volume that you create from BlueXP, System Manager, or the CLI has WORM disabled. If you want to enable WORM on a Cloud Volumes ONTAP working environment that was not enabled during creation, you must create a support ticket with NetApp support for assistance.

Does this update cover the issue?

**Comment by netapp-rlithman** [comment]
I'm going to close the issue. Dariukuss, if you have any other feedback, please let us know. Thank you again.
