### ISSUE TITLE
Additional permission required

### ISSUE THREAD

**Issue by wilshields** [NetAppDocs/cloud-manager-cloud-volumes-ontap#16]
Page: [Get started with Cloud Volumes ONTAP in the AWS C2S environment](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws-c2s.html)

Ben, Can we please get "iam:ListInstanceProfiles" added to policy as a required permission? I hit an issue with AWS where they couldn't subscribe to PayGo because it was missing.

**Comment by netapp-bcammett** [comment]
@wilshields 
I added the permission to the policy for the Connector instance:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws-c2s.html#set-up-permissions

Thank you for letting me know.

Regards,
Ben
