### ISSUE TITLE
Single node system - Managed Disk Options

### ISSUE THREAD

**Issue by fritntap** [NetAppDocs/cloud-manager-cloud-volumes-ontap#165]
Page: [Disks and aggregates](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-storage.html)

Hello, I'm curious if the following statement is accurate:
**Standard SSD Managed Disks provide consistent performance for workloads that require low IOPS.**

Shouldn't this read "require high IOPS", not low IOPS? The reason I ask, the next option (Standard HDD) states that it is a good choice for applications that don't require high IOPS.

In it's current state, the Standard SSD and Standard HDD are the same, for applications that require low IOPS.

Hopefully that makes sense. And again, I could be wrong regarding what we're stating. Thank you.

**Comment by netapp-rlithman** [comment]
It’s written correctly as stated “low”.

All standard storage is for low IOPS requirements.  Standard SSD can provide less variance than HDD.
