### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/cloud-manager-cloud-volumes-ontap#169]
Page: [What’s new](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html)

Throughout this page, there are many instances where the heading syntax is showing and the content isn't formatted as a header. For example:

![image](https://user-images.githubusercontent.com/18287750/231229088-056589f6-d48c-4776-9649-0ac9a6b08828.png)

**Comment by netapp-rlithman** [comment]
I think I know why. I'll update it. Thanks for pointing these out.
