### ISSUE TITLE
Incorrect RTO value

### ISSUE THREAD

**Issue by buslovitch** [NetAppDocs/cloud-manager-cloud-volumes-ontap#190]
Unalignment between statements. In the following document, RTO is 120: 
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha.html#mediator:~:text=The%20recovery%20time%20objective%20(RTO)%20is%20120%20seconds.

In the official eBook we are stating RTO 60:
[Page:](https://www.netapp.com/media/27835-eBook-Disaster-Recovery-CVO.pdf) [Disaster Recovery Challenges]
(https://www.netapp.com/media/27835-eBook-Disaster-Recovery-CVO.pdf)

**Comment by netapp-rlithman** [comment]
Hi. This is a recent change the team asked me to update. I'll refer you to the team for more assistance. I'm going to close this comment.
