### ISSUE TITLE
Link Goes To the Wrong Page?

### ISSUE THREAD

**Issue by BrentADavis** [NetAppDocs/cloud-manager-cloud-volumes-ontap#20]
Page: [Setting up the AWS KMS](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-setting-up-kms.html)

I don’t think the following link is pointing to the right page in the AWS documentation:
https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying.html#key-policy-modifying-external-accounts

**Comment by netapp-bcammett** [comment]
Hi Brent,

Thank you for reaching out and submitting this feedback. I looked at the page and you're right: we need to update the link to the AWS docs. I'll update it and let you know when it's done.

**Comment by netapp-bcammett** [comment]
Brent, the docs have been updated. Thanks again for reaching out!

Regards,
Ben
