### ISSUE TITLE
Can you describe the object storage settings that the Cloud Manager creates? 

### ISSUE THREAD

**Issue by yasuyuki-matsushita** [NetAppDocs/cloud-manager-cloud-volumes-ontap#22]
Page: [Tiering inactive data to low-cost object storage](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html)

Can you describe the object storage settings that the Cloud Manager creates? 
For example, the following information
1.Azure Blob Storage Redundancy. (LRS? ZRS?)
2.The type of storage account .

**Comment by netapp-bcammett** [comment]
@yasuyuki-matsushita
Are you looking for this type of information about the object storage settings in Azure?

> Cloud Manager creates a new storage account with the following settings:
> - Performance: Standard
> - Redundancy: Locally-redundant storage (LRS)
> - Account kind: StorageV2 (general purpose v2)
> - Security:
> 	- Require secure transfer for REST API operations: Enabled
> 	- Storage account key access: Enabled
> 	- Minimum TLS version: Version 1.2
> 	- Infrastructure encryption: Disabled
> - Access tier: Hot

**Comment by yasuyuki-matsushita** [comment]
Thank you for contacting me.
This is the information I was looking for.

Please add the Azure, AWS, and GCP information to the site.
I would like to link sites with this information to my customers.

**Comment by netapp-bcammett** [comment]
Thank you for confirming. I need to find similar information about AWS and Google Cloud and then verify what I've found with the product team. Then I'll update the docs with this information. I'll let you know when it's ready.

**Comment by netapp-bcammett** [comment]
The requested information was added to the following page:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html#data-tiering-in-aws

Thanks again for reaching out with your feedback.

Regards,
Ben
