### ISSUE TITLE
Add-on license statement inaccurate

### ISSUE THREAD

**Issue by scottkntap** [NetAppDocs/cloud-manager-cloud-volumes-ontap#24]
Page: [Manage node-based licenses](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-node-licenses.html)

The statement "_The number of licenses that you can purchase for a single node system or HA pair is unlimited._" while technically accurate, a customer can buy as many licenses as they want, a maximum of 4 add-on licenses can be applied to a node-base BYOL.  Can this sentence please be clarified to reflect the maximum number of add-on licenses?

Thank you!

**Comment by netapp-bcammett** [comment]
Hi Scott,

Thanks for reaching out. I sent a note to my contact on the product team for clarification.

Thanks again,
Ben
