### ISSUE TITLE
Add GCP information

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/cloud-manager-cloud-volumes-ontap#26]
Page: [Manage aggregates](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-aggregates.html)

Hello, would it be possible to add also "Add GCP disks" in the "Add disks to an aggregate" task section ?

**Comment by netapp-bcammett** [comment]
Hi Marco,

Thank you for reaching out. I actually have a draft of the changes ready to go. I was just looking at this a few days ago.

I'll let you know when the changes have been published.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
The page has been updated to be cloud agnostic.

Thanks,
Ben
