### ISSUE TITLE
How to apply marketplace subscriptions

### ISSUE THREAD

**Issue by mgraws** [NetAppDocs/cloud-manager-cloud-volumes-ontap#31]
Page: [Manage capacity-based licenses](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-capacity-licenses.html)

Can you please write how to use marketplace subscriptions when deploying CVO?  This page is all about the digital wallet which does not apply to subscriptions. 

For AWS I received this after asking around.  It would be good to have similar documentation for Azure and GCP.

The marketplace agreement is in AWS and will show up there. They will link that subscription to their Cloud Manager environment and store that as a Cloud Manager subscription with a unique ID as per the standard workflow.
 
When they deploy a CVO cluster, they will assign a marketplace subscription as part of the deployment process which will be the subscription they assigned.

**Comment by netapp-bcammett** [comment]
@mgraws

Thank you for providing this feedback. 

The table on the following page does provide a bit of up-front detail about how you associate a Marketplace subscription (along with the other licensing options):
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-aws.html#before-you-get-started 

But I agree that we could provide more details elsewhere to help users better understand how a marketplace subscription gets applied to Cloud Volumes ONTAP. I'll draft something up and let you know when it's ready.

Thanks again,
Ben
