### ISSUE TITLE
Addition of Capacity Management scope

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-manager-cloud-volumes-ontap#42]
Page: [Storage management](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-storage-management.html)

Could we add in this initial explanation or more suitable place (if exists) which is the range of the Connector settings called "Capacity Management Mode"?
Will it affect to all CVOs being managed/discovered by the Connector?
(Since the change is at Connector level, I will understand the change will affect to all CVOs under same Connector and if I need different Capacity Management modes, I should separate CVOs between different Connectors)

Regards,
Gabriel

**Comment by netapp-bcammett** [comment]
And my apologies for the delay, I was away on vacation :slightly_smiling_face:

**Comment by netapp-bcammett** [comment]
I added the statement in the following section:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-storage-management.html#capacity-management

And on a page that describes how to manage capacity settings for aggregates:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-capacity-settings.html

Thanks again,
Ben
