### ISSUE TITLE
"Enable Capacity Tiering" not available on GCP

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-cloud-volumes-ontap#44]
Page: [Tiering inactive data to low-cost object storage](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html)

It seems that Capacity Tiering can't be enabled post-deployment on GCP.
![image](https://user-images.githubusercontent.com/92466880/171402885-dd6db5ec-4fb9-42ce-ad47-fc1f20844e20.png)

If confirmed, an additional note in the docs would be helpful.

Thx
Holger

**Comment by netapp-bcammett** [comment]
Holger,

I updated the following section:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-cold-data-to-a-google-cloud-storage-bucket

It now includes the following statement:

> If you don’t select a service account during deployment, you’ll need to shut down Cloud Volumes ONTAP, go to the Google Cloud console, and then attach the service account to the Cloud Volumes ONTAP instances. You can then enable data tiering as described in the next section.

I also updated the following section:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html#enabling-data-tiering-after-implementing-the-requirements

It now includes the following statement under step 3:

> In Google Cloud, a service account must be attached to Cloud Volumes ONTAP before this option will appear. [Ensure that you’ve met all requirements](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html#requirements).

Please let me know if you have any additional feedback.

Thanks,
Ben
