### ISSUE TITLE
Availability zone info missing from "Add frontend IP configuration" screen shot

### ISSUE THREAD

**Issue by neilmaldy** [NetAppDocs/cloud-manager-cloud-volumes-ontap#48]
Page: [Create data-serving storage VMs for Cloud Volumes ONTAP in Azure](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html)

The Availability zone pull down is missing from the "Add frontend IP configuration" screen shot.  Also some HA CVOs (older?) use Zone-redundant, and some (newer?) CVOs use No Zone, so can you please document how to choose the proper value?

I'm attaching  a screenshot of the "Add frontend IP configuration" screen for reference:
![Screenshot 2022-06-02 153155](https://user-images.githubusercontent.com/9889606/171723443-1155c42b-78d0-4c0f-b940-0e8a686cafd8.jpg)

Thank you!
Neil Maldonado

**Comment by netapp-bcammett** [comment]
Neil,

Thank you for reaching out. I'll take a look as soon as I have a moment. I'm busy working on a release, so it might be until next week.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
@neilmaldy,

I updated the page as shown in the image below:

![image](https://user-images.githubusercontent.com/18287750/172874227-32efe4e6-8d15-42cf-8a07-cd2b8e31d2c5.png)

Please let me know if you have any additional feedback.

Thanks,
Ben
