### ISSUE TITLE
Need to be more specific how where to put the app.conf file settings.  

### ISSUE THREAD

**Issue by alexmal98** [NetAppDocs/cloud-manager-cloud-volumes-ontap#63]
Page: [Use an Azure Private Link or service endpoints](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-enabling-private-link.html)

It's not clear where to paste the code.  Should it be 'level' with System-id or with "occm"?

**Comment by netapp-bcammett** [comment]
@alexmal98,

Thank you for submitting this feedback. I've reached out to to the product team for clarification. I'll let you know as soon as I hear and then I'll update the docs with the details.

Thanks again,
Ben

**Comment by alexmal98** [comment]
Thanks Ben!

**Comment by netapp-bcammett** [comment]
@alexmal98,

I updated the docs to clearly state that the "user-private-dns-zone-settings" parameter should be entered at the same level as "system-id".

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-enabling-private-link.html#provide-cloud-manager-with-details-about-your-azure-private-dns

Thanks again for submitting this feedback.

Regards,
Ben

**Comment by alexmal98** [comment]
Thanks Ben!
