### ISSUE TITLE
CLI command error for SVM management LIF

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/cloud-manager-cloud-volumes-ontap#66]
Page: [Create data-serving storage VMs for Cloud Volumes ONTAP in Google Cloud](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-gcp.html)

Hello, in step 4 of the SN svm creation there is a little error in the CLI command. The "-home-node node1" field should be indicated as "-home-node <name-of-node1>"

**Comment by netapp-bcammett** [comment]
Hi Marco,

Thank you for submitting this feedback. Can you please clarify what you mean? Are you suggesting that the command shouldn't indicate the name of the node?

I see the following in the man page for "network interface create"

> [-home-node <nodename>] - Home Node
> Use this parameter to specify the LIF's home node. The home node is the node to which the LIF returns when the [network interface revert](https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-9101/network__interface__revert.html) command is run on the LIF.

> cluster1::> network interface create -vserver vs0 -lif datalif1 -home-node node0 -home-port e0c -address 192.0.2.130 -netmask 255.255.255.128 -failover-policy broadcast-domain-wide -service-policy default-data--files -auto-revert true

So I think specifying the name of the node is required. To be consistent, we could update step 4 to use the same notation as step 3: 

> `-home-node <name-of-node1>`

Thanks,
Ben

**Comment by melatsg** [comment]
Hi Ben,

That is exactly what I meant ! 
The command in step 4 is a little bit misleading in my opinion because it seems that the name of the node must be node0.

The notation in step 3 is way better in my opinion.

Thanks

**Comment by netapp-bcammett** [comment]
Marco,

This issue has been fixed.

Thanks,
Ben
