### ISSUE TITLE
Need to highlight ONLY pull down Cloud Volumes ONTAP images

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/cloud-manager-cloud-volumes-ontap#73]
Page: [Upgrade Cloud Volumes ONTAP software](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html)

For #3 on this page: Obtain the software image from [the NetApp Support Site](https://mysupport.netapp.com/products/p/cloud_ontap.html).

We need to put some big notices / warnings that the images should be pulled from "Cloud Volumes ONTAP" not "ONTAP".  Customer pulled down an image from ONTAP which has not been released yet for CVO and it is causing issues.

Only from here: 
![image](https://user-images.githubusercontent.com/519212/180308874-835dad91-1296-4cc9-931d-bc617ad34c19.png)

**Comment by nichollri** [comment]
We should put this link in directly: It should link directly to: https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab

**Comment by netapp-bcammett** [comment]
Thank you, Richard. We actually had a direct link, but the URLs changed and the NSS redirected users to the base products page. I'll use the updated URL that you provided.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
I published the fix a few days ago. 

Thanks again,
Ben
