### ISSUE TITLE
We may have changed mediator GCE type

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-manager-cloud-volumes-ontap#80]
Page: [High-availability pairs in Google Cloud](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-google-cloud.html)

Hi Team, last team I deployed a CVO HA the mediator GCE type was not an f1-micro but an e2-micro.
Not sure if we have changed the default Mediator GCE type or if depending of resources availability on the cloud Cloud Manager decides to use one or the other.

If we have changed the default type of mediator GCE type, could we update the whole document and specially this GCP HA pairs info page?

Thank you,
Gabriel

**Comment by netapp-bcammett** [comment]
This issue has been fixed. Thanks again!
