### ISSUE TITLE
CVO inbound rule purpose addition

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/cloud-manager-cloud-volumes-ontap#85]
Page: [Networking requirements for Cloud Volumes ONTAP in GCP](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/reference-networking-gcp.html)

Hello, I wanted to suggest adding which ports are needed in CVO for the connectivity with the connector. 

In the CVO Inbound rules table I will change the purpose details from “HTTP/S access to the System Manager web console using the IP address of the cluster management LIF” to something like “HTTP/S access to the System Manager web console using the IP address of the cluster management LIF and connectivity with the connector”

I believe that someone may think that port 80 and 443 are needed only to access System Manager and so can be closed if they don’t want to manage CVO with such a tool.

Thanks

**Comment by netapp-bcammett** [comment]
Thank you for the suggestion, Marco. I'll get this change in soon.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
Marco,

I updated the description of port 443 to note that it's used for inbound connections from the Connector (port 80 isn't used). 

![image](https://user-images.githubusercontent.com/18287750/185146199-16081e1f-c790-4138-886e-4b1f2a263252.png)

I made this change for all cloud providers.

Thanks,
Ben
