### ISSUE TITLE
flexgroup volumes in cloud manager are no longer visible

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/cloud-manager-cloud-volumes-ontap#89]
Page: [Known limitations](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/reference-limitations.html)

Hello Team,

In the latest version of cloud manager, FG volumes are no longer visible in CM and therefore don`t require any capacity mode settings. Could we please update the docs to simply say "fg volumes are not visible in cm and can only be managed via sysmanager or cli" ?

Note: this has been tested in a lab and verified.

**Comment by netapp-bcammett** [comment]
@laagabi,

After speaking with our product management team, the note about capacity management stays the same. It's true that FlexGroup volumes no longer appear in the interface, but there are no changes to how these volumes interact with the capacity mode settings.

Thanks,
Ben
