### ISSUE TITLE
Add information about how customer will receive serial numbers/licenses

### ISSUE THREAD

**Issue by felix-melligan** [NetAppDocs/cloud-manager-cloud-volumes-ontap#9]
Page: [Manage licenses for Cloud Volumes ONTAP](https://docs.netapp.com/us-en/occm/task_managing_licenses.html)

**Comment by netapp-bcammett** [comment]
A new section has been added to the top of the page.
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-capacity-licenses.html

Thanks,
Ben
