### ISSUE TITLE
Upgrading via HTTPS URL needs a custom certifcate

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/cloud-manager-cloud-volumes-ontap#91]
Page: [Upgrade Cloud Volumes ONTAP software](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html)

Hi Team,

Currently, when users are trying to use HTTPS to host ontap images, it will fail due to SSL authentication issues which are caused by missing certificates. A workaround has been captured in the below kb:
https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/How_to_configure_Cloud_Manager_as_an_HTTPS_server_to_host_upgrade_images

The ask is to update the doc to make users aware of this. Perhaps we could referenece the kb above?

**Comment by netapp-bcammett** [comment]
Gabor,

Thank you for letting me know about this. I updated the page by describing the issue and linking to the KB article. You can find the text in the following section under Before you begin:

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrade-from-an-image-available-at-a-url

Thanks again,
Ben

**Comment by laagabi** [comment]
Thank You Ben,

Looks awesome! Thanks for the speedy response!

BR,
Gabor.
