### ISSUE TITLE
Japanese version look and feel gets broken

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-manager-cloud-volumes-ontap#94]
Page: [Google Cloud の Cloud Volumes ONTAP のクイックスタート](https://docs.netapp.com/ja-jp/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html)

When changing from English a page like this (with icons, lists, embedded symbols etc) to Japanese version the format, translation and texts get affected making difficult to read and understand.

English:
![image](https://user-images.githubusercontent.com/34706481/191637081-527b7d6a-bc0b-481f-baf5-c74de458b73f.png)

Japanese:
![image](https://user-images.githubusercontent.com/34706481/191637114-9d652beb-bd25-4384-a44d-0ea223ecf7ec.png)

I see this problem happens in more pages of the document and it may be complicated to fix but improving it will help readability.

Regards,
Gabriel

**Comment by netapp-bcammett** [comment]
@netapp-gudugunti,
Same as https://github.com/NetAppDocs/cloud-manager-setup-admin/issues/75

cc: @ntap-bmegan

**Comment by ntap-bmegan** [comment]
This was fixed some time back. 



![Image](https://user-images.githubusercontent.com/56453501/226881918-8de5b22c-cc14-4c67-bae6-5829d36c232c.png)
