### ISSUE TITLE
Upgrade image from URL - upgrade package location on connector is incorrect

### ISSUE THREAD

**Issue by dismn8r** [NetAppDocs/cloud-manager-cloud-volumes-ontap#99]
Page: [Upgrade Cloud Volumes ONTAP software](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html)

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrade-from-an-image-available-at-a-url

Software package location is listed as ...
/opt/application/netapp/cloudmanager/docker_occm/data/ontap/images/

It should be ...
/opt/application/netapp/cloudmanager/ontap/images/

Cheers,
Jason Drury

**Comment by netapp-rlithman** [comment]
The page has now been updated to include both software package locations. Jason, thank you for your help with this. 

[Upgrade Cloud Volumes ONTAP](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrade-from-an-image-available-at-a-url)
